#Main server file

import os
import json
from flask import Flask, render_template, request, session, flash, g, redirect, url_for
from flask_restful import reqparse, abort, Api, Resource

from models import db, User, Report, Kanji

app = Flask(__name__)
api = Api(app)

app.config.update(dict(SEND_FILE_MAX_AGE_DEFAULT=0))

SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(app.root_path, 'server.db')

app.config.from_object(__name__)
app.config.from_envvar('SERVER_SETTINGS', silent=True)
app.debug = True

db.init_app(app)

@app.cli.command('initdb')
def initdb_command():
	db.drop_all()
	db.create_all()
	add_data()
	#db.session.commit()
	print("Initialized the database")

@app.before_request
def before_request():
	#Check if a user is in session
	g.user = None
	if 'userID' in session:
		g.user = User.query.filter_by(userID=session['userID']).first()

@app.route("/", methods = ['GET', 'POST'])
def rootpage():
	#Check if the user is already in session
	if g.user:
		return redirect(url_for('home', username = g.user.username))
	error = None
	if request.method == 'POST':
		#Check if a username was entered- extra precautions
		if request.form['name'] is None:
			error = "Please enter a username"
		else:
			#Check for valid username
			name = User.query.filter_by(userID = request.form['name']).first()
			if name is None:
				error = "Invalid credentials"
			#Check for a password
			elif not request.form['pass']:
				error = "Please enter a password"
			#Check for correct password
			elif name.password == request.form['pass']:
				session['userID'] = name.userID
				flash("You have been logged in")
				return redirect(url_for('home', username = name.userID))
			else:
				error = "Invalid credentials"
	
	return render_template("login.html")

@app.route("/<userID>/", methods=['GET', 'POST'])
def home(userID):
	if g.user:
		#Make sure this is the correct user
		if userID == g.user.userID:
			error = None
			if request.method == "POST":
				#Add a new chatroom
				chat = ChatRoom.query.filter_by(title = request.form['title']).first()
				if not request.form['title']:
					#Check that a title has been added
					error = "Please enter a title"
				elif chat is not None:
					error = "That title already exists"
				else:
					#Note: chatrooms can have the same titles, does not affect overall implementation
					newChat = ChatRoom(request.form['title'], g.user.user_id)
					db.session.add(newChat)
					g.user.chatrooms.append(newChat)
					db.session.commit()
			return render_template('home.html')
		else:
			abort(401)
	#If no one is in session, redirect to the root page
	else:
		return redirect(url_for('rootpage'))


#Route to the signup page, redirect to profile page if in session	
@app.route("/sign_up/", methods = ['GET', 'POST'])
def sign_up():
	if g.user:
		return redirect(url_for('home', username=g.user.userID))
	error = None
	if request.method == 'POST':
		#Check for username
		if not request.form['name']:
			error = "Please enter a username"
		#Check for a password
		elif not request.form['pass']:
			error = "Please enter a password"
		#Check for a reentered password
		elif not request.form['pass2']:
			error = "Please reenter your password"
		#Check the passwords match
		elif request.form['pass'] != request.form['pass2']:
			error = "Passwords do not match"
		#Check for taken username
		elif get_user_id(request.form['name']) is None:
			db.session.add(User(request.form['name'], request.form['pass']))
			db.session.commit()
			return redirect(url_for('rootpage'))
		else:
			error = "That username is already taken"
	return render_template("signup.html", error = error)

def add_data():
	db.session.add(Kanji(1, '海岸','kaigan'))
	db.session.add(Kanji(2, '学期','gakki'))
	db.session.add(Kanji(3, '時期','jiki'))
	db.session.add(Kanji(4, '期間','kikan'))
	db.session.add(Kanji(5, '期待','kitai'))
	db.session.add(Kanji(6, '期末','kimatsu'))
	db.session.add(Kanji(7, '',''))
	db.session.add(Kanji(8, '',''))
	db.session.add(Kanji(9, '',''))
	db.session.add(Kanji(10, '',''))
	db.session.add(Kanji(11, '',''))
	db.session.add(Kanji(12, '',''))
	db.session.add(Kanji(13, '',''))
	db.session.add(Kanji(14, '',''))
	db.session.add(Kanji(15, '',''))
	db.session.add(Kanji(16, '',''))
	db.session.add(Kanji(17, '',''))
	db.session.add(Kanji(18, '',''))
	db.session.add(Kanji(19, '',''))
	db.session.add(Kanji(20, '',''))
	db.session.add(Kanji(21, '',''))
	db.session.add(Kanji(22, '',''))
	db.session.add(Kanji(23, '',''))
	db.session.add(Kanji(24, '',''))
	db.session.add(Kanji(25, '',''))
	db.session.add(Kanji(26, '',''))
	db.session.add(Kanji(27, '',''))
	db.session.add(Kanji(28, '',''))
	db.session.add(Kanji(29, '',''))
	db.session.add(Kanji(30, '',''))
	db.session.add(Kanji(31, '',''))
	db.session.add(Kanji(32, '',''))
	db.session.add(Kanji(33, '',''))
	db.session.add(Kanji(34, '',''))
	db.session.add(Kanji(35, '',''))
	db.session.add(Kanji(36, '',''))
	db.session.add(Kanji(37, '',''))
	db.session.add(Kanji(38, '',''))
	db.session.add(Kanji(39, '',''))
	db.session.add(Kanji(40, '',''))
	db.session.add(Kanji(41, '',''))
	db.session.add(Kanji(42, '',''))
	db.session.add(Kanji(43, '',''))
	db.session.add(Kanji(44, '',''))
	db.session.add(Kanji(45, '',''))
	db.session.add(Kanji(46, '',''))
	db.session.add(Kanji(47, '',''))
	db.session.add(Kanji(48, '',''))
	db.session.add(Kanji(49, '',''))
	db.session.add(Kanji(50, '',''))
	db.session.add(Kanji(51, '',''))
	db.session.add(Kanji(52, '',''))
	db.session.add(Kanji(53, '',''))
	db.session.add(Kanji(54, '',''))
	db.session.add(Kanji(55, '',''))
	db.session.add(Kanji(56, '',''))
	db.session.add(Kanji(57, '',''))
	db.session.add(Kanji(58, '',''))
	db.session.add(Kanji(59, '',''))
	db.session.add(Kanji(60, '',''))
	db.session.add(Kanji(61, '',''))
	db.session.add(Kanji(62, '',''))
	db.session.add(Kanji(63, '',''))
	db.session.add(Kanji(64, '',''))
	db.session.add(Kanji(65, '',''))
	db.session.add(Kanji(66, '',''))
	db.session.add(Kanji(67, '',''))
	db.session.add(Kanji(68, '',''))
	db.session.add(Kanji(69, '',''))
	db.session.add(Kanji(70, '',''))
	db.session.add(Kanji(71, '',''))
	db.session.add(Kanji(72, '',''))
	db.session.add(Kanji(73, '',''))
	db.session.add(Kanji(74, '',''))
	db.session.add(Kanji(75, '',''))
	db.session.add(Kanji(76, '',''))
	db.session.add(Kanji(77, '',''))
	db.session.add(Kanji(78, '',''))
	db.session.add(Kanji(79, '',''))
	db.session.add(Kanji(80, '',''))
	db.session.add(Kanji(81, '',''))
	db.session.add(Kanji(82, '',''))
	db.session.add(Kanji(83, '',''))
	db.session.add(Kanji(84, '',''))
	db.session.add(Kanji(85, '',''))
	db.session.add(Kanji(86, '',''))
	db.session.add(Kanji(87, '',''))
	db.session.add(Kanji(88, '',''))
	db.session.add(Kanji(89, '',''))
	db.session.add(Kanji(90, '',''))
	db.session.add(Kanji(91, '',''))
	db.session.add(Kanji(92, '',''))
	db.session.add(Kanji(93, '',''))
	db.session.add(Kanji(94, '',''))
	db.session.add(Kanji(95, '',''))
	db.session.add(Kanji(96, '',''))
	db.session.add(Kanji(97, '',''))
	db.session.add(Kanji(98, '',''))
	db.session.add(Kanji(99, '',''))
	db.session.add(Kanji(100, '',''))
	db.session.add(Kanji(101, '',''))
	db.session.add(Kanji(102, '',''))
	db.session.add(Kanji(103, '',''))
	db.session.add(Kanji(104, '',''))
	db.session.add(Kanji(105, '',''))
	db.session.add(Kanji(106, '',''))
	db.session.add(Kanji(107, '',''))
	db.session.add(Kanji(108, '',''))
	db.session.add(Kanji(109, '',''))
	db.session.add(Kanji(110, '',''))
	db.session.add(Kanji(111, '',''))
	db.session.add(Kanji(112, '',''))
	db.session.add(Kanji(113, '',''))
	db.session.add(Kanji(114, '',''))
	db.session.add(Kanji(115, '',''))
	db.session.add(Kanji(116, '',''))
	db.session.add(Kanji(117, '',''))
	db.session.add(Kanji(118, '',''))
	db.session.add(Kanji(119, '',''))
	db.session.add(Kanji(120, '',''))
	db.session.add(Kanji(121, '',''))
	db.session.add(Kanji(122, '',''))
	db.session.add(Kanji(123, '',''))
	db.session.add(Kanji(124, '',''))
	db.session.add(Kanji(125, '',''))
	db.session.add(Kanji(126, '',''))
	db.session.add(Kanji(127, '',''))
	db.session.add(Kanji(128, '',''))
	db.session.add(Kanji(129, '',''))
	db.session.add(Kanji(130, '',''))
	db.session.add(Kanji(131, '',''))
	db.session.add(Kanji(132, '',''))
	db.session.add(Kanji(133, '',''))
	db.session.add(Kanji(134, '',''))
	db.session.add(Kanji(135, '',''))
	db.session.add(Kanji(136, '',''))
	db.session.add(Kanji(137, '',''))
	db.session.add(Kanji(138, '',''))
	db.session.add(Kanji(139, '',''))
	db.session.add(Kanji(140, '',''))
	db.session.add(Kanji(141, '',''))
	db.session.add(Kanji(142, '',''))
	db.session.add(Kanji(143, '',''))
	db.session.add(Kanji(144, '',''))
	db.session.add(Kanji(145, '',''))
	db.session.add(Kanji(146, '',''))
	db.session.add(Kanji(147, '',''))
	db.session.add(Kanji(148, '',''))
	db.session.add(Kanji(149, '',''))
	db.session.add(Kanji(150, '',''))
	db.session.add(Kanji(151, '',''))
	db.session.add(Kanji(152, '',''))
	db.session.add(Kanji(153, '',''))
	db.session.add(Kanji(154, '',''))
	db.session.add(Kanji(155, '',''))
	db.session.add(Kanji(156, '',''))
	db.session.add(Kanji(157, '',''))
	db.session.add(Kanji(158, '',''))
	db.session.add(Kanji(159, '',''))
	db.session.add(Kanji(160, '',''))
	db.session.add(Kanji(161, '',''))
	db.session.add(Kanji(162, '',''))
	db.session.add(Kanji(163, '',''))
	db.session.add(Kanji(164, '',''))
	db.session.add(Kanji(165, '',''))
	db.session.add(Kanji(166, '',''))
	db.session.add(Kanji(167, '',''))
	db.session.add(Kanji(168, '',''))
	db.session.add(Kanji(169, '',''))
	db.session.add(Kanji(170, '',''))
	db.session.add(Kanji(171, '',''))
	db.session.add(Kanji(172, '',''))
	db.session.add(Kanji(173, '',''))
	db.session.add(Kanji(174, '',''))
	db.session.add(Kanji(175, '',''))
	db.session.add(Kanji(176, '',''))
	db.session.add(Kanji(177, '',''))
	db.session.add(Kanji(178, '',''))
	db.session.add(Kanji(179, '',''))
	db.session.add(Kanji(180, '',''))
	db.session.add(Kanji(181, '',''))
	db.session.add(Kanji(182, '',''))
	db.session.add(Kanji(183, '',''))
	db.session.add(Kanji(184, '',''))
	db.session.add(Kanji(185, '',''))
	db.session.add(Kanji(186, '',''))
	db.session.add(Kanji(187, '',''))
	db.session.add(Kanji(188, '',''))
	db.session.add(Kanji(189, '',''))
	db.session.add(Kanji(190, '',''))
	db.session.add(Kanji(191, '',''))
	db.session.add(Kanji(192, '',''))
	db.session.add(Kanji(193, '',''))
	db.session.add(Kanji(194, '',''))
	db.session.add(Kanji(195, '',''))
	db.session.add(Kanji(196, '',''))
	db.session.add(Kanji(197, '',''))
	db.session.add(Kanji(198, '',''))
	db.session.add(Kanji(199, '',''))
	db.session.add(Kanji(200, '',''))
	db.session.add(Kanji(201, '',''))
	db.session.add(Kanji(202, '',''))
	db.session.add(Kanji(203, '',''))
	db.session.add(Kanji(204, '',''))
	db.session.add(Kanji(205, '',''))
	db.session.add(Kanji(206, '',''))
	db.session.add(Kanji(207, '',''))
	db.session.add(Kanji(208, '',''))
	db.session.add(Kanji(209, '',''))
	db.session.add(Kanji(210, '',''))
	db.session.add(Kanji(211, '',''))
	db.session.add(Kanji(212, '',''))
	db.session.add(Kanji(213, '',''))
	db.session.add(Kanji(214, '',''))
	db.session.add(Kanji(215, '',''))
	db.session.add(Kanji(216, '',''))
	db.session.add(Kanji(217, '',''))
	db.session.add(Kanji(218, '',''))
	db.session.add(Kanji(219, '',''))
	db.session.add(Kanji(220, '',''))
	db.session.add(Kanji(221, '',''))
	db.session.add(Kanji(222, '',''))
	db.session.add(Kanji(223, '',''))
	db.session.add(Kanji(224, '',''))
	db.session.add(Kanji(225, '',''))
	db.session.add(Kanji(226, '',''))
	db.session.add(Kanji(227, '',''))
	db.session.add(Kanji(228, '',''))
	db.session.add(Kanji(229, '',''))
	db.session.add(Kanji(230, '',''))
	db.session.add(Kanji(231, '',''))
	db.session.add(Kanji(232, '',''))
	db.session.add(Kanji(233, '',''))
	db.session.add(Kanji(234, '',''))
	db.session.add(Kanji(235, '',''))
	db.session.add(Kanji(236, '',''))
	db.session.add(Kanji(237, '',''))
	db.session.add(Kanji(238, '',''))
	db.session.add(Kanji(239, '',''))
	db.session.add(Kanji(240, '',''))
	db.session.add(Kanji(241, '',''))
	db.session.add(Kanji(242, '',''))
	db.session.add(Kanji(243, '',''))
	db.session.add(Kanji(244, '',''))
	db.session.add(Kanji(245, '',''))
	db.session.add(Kanji(246, '',''))
	db.session.add(Kanji(247, '',''))
	db.session.add(Kanji(248, '',''))
	db.session.add(Kanji(249, '',''))
	db.session.add(Kanji(250, '',''))
	db.session.add(Kanji(251, '',''))
	db.session.add(Kanji(252, '',''))
	db.session.add(Kanji(253, '',''))
	db.session.add(Kanji(254, '',''))
	db.session.add(Kanji(255, '',''))
	db.session.add(Kanji(256, '',''))
	db.session.add(Kanji(257, '',''))
	db.session.add(Kanji(258, '',''))
	db.session.add(Kanji(259, '',''))
	db.session.add(Kanji(260, '',''))
	db.session.add(Kanji(261, '',''))
	db.session.add(Kanji(262, '',''))
	db.session.add(Kanji(263, '',''))
	db.session.add(Kanji(264, '',''))
	db.session.add(Kanji(265, '',''))
	db.session.add(Kanji(266, '',''))
	db.session.add(Kanji(267, '',''))
	db.session.add(Kanji(268, '',''))
	db.session.add(Kanji(269, '',''))
	db.session.add(Kanji(270, '',''))
	db.session.add(Kanji(271, '',''))
	db.session.add(Kanji(272, '',''))
	db.session.add(Kanji(273, '',''))
	db.session.add(Kanji(274, '',''))
	db.session.add(Kanji(275, '',''))
	db.session.add(Kanji(276, '',''))
	db.session.add(Kanji(277, '',''))
	db.session.add(Kanji(278, '',''))
	db.session.add(Kanji(279, '',''))
	db.session.add(Kanji(280, '',''))
	db.session.add(Kanji(281, '',''))
	db.session.add(Kanji(282, '',''))
	db.session.add(Kanji(283, '',''))
	db.session.add(Kanji(284, '',''))
	db.session.add(Kanji(285, '',''))
	db.session.add(Kanji(286, '',''))
	db.session.add(Kanji(287, '',''))
	db.session.add(Kanji(288, '',''))
	db.session.add(Kanji(289, '',''))
	db.session.add(Kanji(290, '',''))
	db.session.add(Kanji(291, '',''))
	db.session.add(Kanji(292, '',''))
	db.session.add(Kanji(293, '',''))
	db.session.add(Kanji(294, '',''))
	db.session.add(Kanji(295, '',''))
	db.session.add(Kanji(296, '',''))
	db.session.add(Kanji(297, '',''))
	db.session.add(Kanji(298, '',''))
	db.session.add(Kanji(299, '',''))
	db.session.add(Kanji(300, '',''))
	db.session.add(Kanji(301, '',''))
	db.session.add(Kanji(302, '',''))
	db.session.add(Kanji(303, '',''))
	db.session.add(Kanji(304, '',''))
	db.session.add(Kanji(305, '',''))
	db.session.add(Kanji(306, '',''))
	db.session.add(Kanji(307, '',''))
	db.session.add(Kanji(308, '',''))
	db.session.add(Kanji(309, '',''))
	db.session.add(Kanji(310, '',''))
	db.session.add(Kanji(311, '',''))
	db.session.add(Kanji(312, '',''))
	db.session.add(Kanji(313, '',''))
	db.session.add(Kanji(314, '',''))
	db.session.add(Kanji(315, '',''))
	db.session.add(Kanji(316, '',''))
	db.session.add(Kanji(317, '',''))
	db.session.add(Kanji(318, '',''))
	db.session.add(Kanji(319, '',''))
	db.session.add(Kanji(320, '',''))
	db.session.add(Kanji(321, '',''))
	db.session.add(Kanji(322, '',''))
	db.session.add(Kanji(323, '',''))
	db.session.add(Kanji(324, '',''))
	db.session.add(Kanji(325, '',''))
	db.session.add(Kanji(326, '',''))
	db.session.add(Kanji(327, '',''))
	db.session.add(Kanji(328, '',''))
	db.session.add(Kanji(329, '',''))
	db.session.add(Kanji(330, '',''))
	db.session.add(Kanji(331, '',''))
	db.session.add(Kanji(332, '',''))
	db.session.add(Kanji(333, '',''))
	db.session.add(Kanji(334, '',''))
	db.session.add(Kanji(335, '',''))
	db.session.add(Kanji(336, '',''))
	db.session.add(Kanji(337, '',''))
	db.session.add(Kanji(338, '',''))
	db.session.add(Kanji(339, '',''))
	db.session.add(Kanji(340, '',''))
	db.session.add(Kanji(341, '',''))
	db.session.add(Kanji(342, '',''))
	db.session.add(Kanji(343, '',''))
	db.session.add(Kanji(344, '',''))
	db.session.add(Kanji(345, '',''))
	db.session.add(Kanji(346, '',''))
	db.session.add(Kanji(347, '',''))
	db.session.add(Kanji(348, '',''))
	db.session.add(Kanji(349, '',''))
	db.session.add(Kanji(350, '',''))
	db.session.add(Kanji(351, '',''))
	db.session.add(Kanji(352, '',''))
	db.session.add(Kanji(353, '',''))
	db.session.add(Kanji(354, '',''))
	db.session.add(Kanji(355, '',''))
	db.session.add(Kanji(356, '',''))
	db.session.add(Kanji(357, '',''))
	db.session.add(Kanji(358, '',''))
	db.session.add(Kanji(359, '',''))
	db.session.add(Kanji(360, '',''))
	db.session.add(Kanji(361, '',''))
	db.session.add(Kanji(362, '',''))
	db.session.add(Kanji(363, '',''))
	db.session.add(Kanji(364, '',''))
	db.session.add(Kanji(365, '',''))
	db.session.add(Kanji(366, '',''))
	db.session.add(Kanji(367, '',''))
	db.session.add(Kanji(368, '',''))
	db.session.add(Kanji(369, '',''))
	db.session.add(Kanji(370, '',''))
	db.session.add(Kanji(371, '',''))
	db.session.add(Kanji(372, '',''))
	db.session.add(Kanji(373, '',''))
	db.session.add(Kanji(374, '',''))
	db.session.add(Kanji(375, '',''))
	db.session.add(Kanji(376, '',''))
	db.session.add(Kanji(377, '',''))
	db.session.add(Kanji(378, '',''))
	db.session.add(Kanji(379, '',''))
	db.session.add(Kanji(380, '',''))
	db.session.add(Kanji(381, '',''))
	db.session.add(Kanji(382, '',''))
	db.session.add(Kanji(383, '',''))
	db.session.add(Kanji(384, '',''))
	db.session.add(Kanji(385, '',''))
	db.session.add(Kanji(386, '',''))
	db.session.add(Kanji(387, '',''))
	db.session.add(Kanji(388, '',''))
	db.session.add(Kanji(389, '',''))
	db.session.add(Kanji(390, '',''))
	db.session.add(Kanji(391, '',''))
	db.session.add(Kanji(392, '',''))
	db.session.add(Kanji(393, '',''))
	db.session.add(Kanji(394, '',''))
	db.session.add(Kanji(395, '',''))
	db.session.add(Kanji(396, '',''))
	db.session.add(Kanji(397, '',''))
	db.session.add(Kanji(398, '',''))
	db.session.add(Kanji(399, '',''))
	db.session.add(Kanji(400, '',''))
	db.session.add(Kanji(401, '',''))
	db.session.add(Kanji(402, '',''))
	db.session.add(Kanji(403, '',''))
	db.session.add(Kanji(404, '',''))
	db.session.add(Kanji(405, '',''))
	db.session.add(Kanji(406, '',''))
	db.session.add(Kanji(407, '',''))
	db.session.add(Kanji(408, '',''))
	db.session.add(Kanji(409, '',''))
	db.session.add(Kanji(410, '',''))
	db.session.add(Kanji(411, '',''))
	db.session.add(Kanji(412, '',''))
	db.session.add(Kanji(413, '',''))
	db.session.add(Kanji(414, '',''))
	db.session.add(Kanji(415, '',''))
	db.session.add(Kanji(416, '',''))
	db.session.add(Kanji(417, '',''))
	db.session.add(Kanji(418, '',''))
	db.session.add(Kanji(419, '',''))
	db.session.add(Kanji(420, '',''))
	db.session.add(Kanji(421, '',''))
	db.session.add(Kanji(422, '',''))
	db.session.add(Kanji(423, '',''))
	db.session.add(Kanji(424, '',''))
	db.session.add(Kanji(425, '',''))
	db.session.add(Kanji(426, '',''))
	db.session.add(Kanji(427, '',''))
	db.session.add(Kanji(428, '',''))
	db.session.add(Kanji(429, '',''))
	db.session.add(Kanji(430, '',''))
	db.session.add(Kanji(431, '',''))
	db.session.add(Kanji(432, '',''))
	db.session.add(Kanji(433, '',''))
	db.session.add(Kanji(434, '',''))
	db.session.add(Kanji(435, '',''))
	db.session.add(Kanji(436, '',''))
	db.session.add(Kanji(437, '',''))
	db.session.add(Kanji(438, '',''))
	db.session.add(Kanji(439, '',''))
	db.session.add(Kanji(440, '',''))
	db.session.add(Kanji(441, '',''))
	db.session.add(Kanji(442, '',''))
	db.session.add(Kanji(443, '',''))
	db.session.add(Kanji(444, '',''))
	db.session.add(Kanji(445, '',''))
	db.session.add(Kanji(446, '',''))
	db.session.add(Kanji(447, '',''))
	db.session.add(Kanji(448, '',''))
	db.session.add(Kanji(449, '',''))
	db.session.add(Kanji(450, '',''))
	db.session.add(Kanji(451, '',''))
	db.session.add(Kanji(452, '',''))
	db.session.add(Kanji(453, '',''))
	db.session.add(Kanji(454, '',''))
	db.session.add(Kanji(455, '',''))
	db.session.add(Kanji(456, '',''))
	db.session.add(Kanji(457, '',''))
	db.session.add(Kanji(458, '',''))
	db.session.add(Kanji(459, '',''))
	db.session.add(Kanji(460, '',''))
	db.session.add(Kanji(461, '',''))
	db.session.add(Kanji(462, '',''))
	db.session.add(Kanji(463, '',''))
	db.session.add(Kanji(464, '',''))
	db.session.add(Kanji(465, '',''))
	db.session.add(Kanji(466, '',''))
	db.session.add(Kanji(467, '',''))
	db.session.add(Kanji(468, '',''))
	db.session.add(Kanji(469, '',''))
	db.session.add(Kanji(470, '',''))
	db.session.add(Kanji(471, '',''))
	db.session.add(Kanji(472, '',''))
	db.session.add(Kanji(473, '',''))
	db.session.add(Kanji(474, '',''))
	db.session.add(Kanji(475, '',''))
	db.session.add(Kanji(476, '',''))
	db.session.add(Kanji(477, '',''))
	db.session.add(Kanji(478, '',''))
	db.session.add(Kanji(479, '',''))
	db.session.add(Kanji(480, '',''))
	db.session.add(Kanji(481, '',''))
	db.session.add(Kanji(482, '',''))
	db.session.add(Kanji(483, '',''))
	db.session.add(Kanji(484, '',''))
	db.session.add(Kanji(485, '',''))
	db.session.add(Kanji(486, '',''))
	db.session.add(Kanji(487, '',''))
	db.session.add(Kanji(488, '',''))
	db.session.add(Kanji(489, '',''))
	db.session.add(Kanji(490, '',''))
	db.session.add(Kanji(491, '',''))
	db.session.add(Kanji(492, '',''))
	db.session.add(Kanji(493, '',''))
	db.session.add(Kanji(494, '',''))
	db.session.add(Kanji(495, '',''))
	db.session.add(Kanji(496, '',''))
	db.session.add(Kanji(497, '',''))
	db.session.add(Kanji(498, '',''))
	db.session.add(Kanji(499, '',''))
	db.session.add(Kanji(500, '',''))
	db.session.commit()
